# Generated by Django 4.1b1 on 2022-07-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemperatureReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
            ],
            options={
                "db_table": "temperature_reading",
                "get_latest_by": ["-timestamp", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="temperaturereading",
            index=models.Index(fields=["timestamp"], name="timestamp_idx"),
        ),
    ]
